### ISSUE TITLE
package org.bouncycastle.jce.provider does not exist

### ISSUE THREAD

**Issue by kildonan5** [NetSPI/WebLogicPasswordDecryptor#4]
Trying to compile the java version and getting this error. Could you provide some guidance? Also is there some way to verify that the DLL is from BouncyCastle i.e. a file integrity hash to check against the bouncy castle resources to know it came from them?

**Comment by egru** [comment]
You'll need to import the package from maven or by including the jar file. You can get it here: https://www.bouncycastle.org/latest_releases.html.

I don't have the hash for the DLL. I don't actually remember which version it is, but you can download the latest DLL from here: https://www.bouncycastle.org/csharp/index.html. Hopefully it should still work.

**Comment by kildonan5** [comment]
including the bouncycastle jar files in my classpath did the trick, thanks.
